version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    environment:
      - PROD=True
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    tty: true
    restart: on-failure
  db:
   image: postgres:11.5-alpine
   environment:
     - POSTGRES_USER=username
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=dbname
   volumes:
     - data:/var/lib/postgresql/data
   expose:
     - "5432"
volumes:
  data: