# Generated by Django 3.0.1 on 2019-12-27 09:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Depth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subareas', models.ManyToManyField(related_name='universes', to='data_parser.Subarea')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Universe')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('depths', models.ManyToManyField(related_name='stats', to='data_parser.Depth')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('comment', models.TextField(null=True)),
                ('datasets', models.ManyToManyField(related_name='products', to='data_parser.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='PlotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stats', models.ManyToManyField(related_name='plot_types', to='data_parser.Stat')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Area')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Dataset')),
                ('depth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Depth')),
                ('plot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.PlotType')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Product')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Stat')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Subarea')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Universe')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=32)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('product', models.CharField(max_length=256)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Area')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Variable')),
            ],
        ),
        migrations.AddField(
            model_name='depth',
            name='products',
            field=models.ManyToManyField(related_name='depths', to='data_parser.Product'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Variable'),
        ),
    ]
