# Generated by Django 3.0.2 on 2020-01-29 18:37

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Depth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('catalogue_url', models.CharField(max_length=512)),
                ('documentation_url', models.CharField(max_length=512, null=True)),
                ('comment', models.TextField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='data_parser.Area')),
                ('datasets', models.ManyToManyField(related_name='products', to='data_parser.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('areas', models.ManyToManyField(related_name='universes', to='data_parser.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='data_parser.Universe')),
            ],
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='data_parser.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('depths', models.ManyToManyField(related_name='stats', to='data_parser.Depth')),
            ],
        ),
        migrations.CreateModel(
            name='PlotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stats', models.ManyToManyField(related_name='plot_types', to='data_parser.Stat')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Area')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Dataset')),
                ('depth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Depth')),
                ('plot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.PlotType')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Product')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Stat')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Subarea')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Universe')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='KpiScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('MSD_FCST12', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('MSD_HDCT', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('MS_OBS', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('MEAN_OBS', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('NB_OBS', models.IntegerField(null=True)),
                ('MSD_CLIM', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Area')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Dataset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Product')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='KpiSat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat', models.CharField(max_length=32)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Area')),
            ],
        ),
        migrations.CreateModel(
            name='KpiInsitu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=32)),
                ('product', models.CharField(max_length=256)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Area')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Variable')),
            ],
        ),
        migrations.AddField(
            model_name='depth',
            name='subareas',
            field=models.ManyToManyField(related_name='depths', to='data_parser.Subarea'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='data_parser.Variable'),
        ),
    ]
