# Generated by Django 2.2.7 on 2019-11-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Depth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Univers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('univers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Univers')),
            ],
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('depth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Depth')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='PlotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Stat')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Area')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Dataset')),
                ('depth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Depth')),
                ('plot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.PlotType')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Product')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Stat')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Subarea')),
                ('univers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Univers')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Variable')),
            ],
        ),
        migrations.AddField(
            model_name='depth',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Product'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Variable'),
        ),
    ]
