# Generated by Django 3.0.2 on 2020-01-24 18:46

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=32)),
                ('product', models.CharField(max_length=256)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Area')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='KpiSat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat', models.CharField(max_length=32)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Area')),
            ],
        ),
    ]
