# Generated by Django 3.0.1 on 2020-01-08 14:55

import apps.data_parser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='kind',
            field=models.CharField(choices=[(apps.data_parser.models.KpiKindChoice['INSITU'], 'INSITU'), (apps.data_parser.models.KpiKindChoice['SAT'], 'SAT'), (apps.data_parser.models.KpiKindChoice['SKILL_SCORE'], 'SKILL_SCORE')], default=apps.data_parser.models.KpiKindChoice['INSITU'], max_length=32),
        ),
    ]
