# Generated by Django 2.2.7 on 2019-11-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='depth',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plottype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='stat',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='univers',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
