# Generated by Django 3.0.2 on 2020-01-23 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0002_kpi_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='kpi',
            name='end_date_str',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='start_date_str',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
