# Generated by Django 3.0.2 on 2020-01-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0003_auto_20200123_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
