# Generated by Django 2.2.7 on 2019-11-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0003_product_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dataset',
        ),
        migrations.AddField(
            model_name='product',
            name='datasets',
            field=models.ManyToManyField(to='data_parser.Dataset'),
        ),
    ]
