# Generated by Django 2.2.7 on 2019-11-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0004_auto_20191127_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Comment',
            new_name='comment',
        ),
    ]
