# Generated by Django 2.2.7 on 2019-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0005_auto_20191127_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depth',
            name='product',
        ),
        migrations.AddField(
            model_name='depth',
            name='products',
            field=models.ManyToManyField(to='data_parser.Product'),
        ),
        migrations.RemoveField(
            model_name='plottype',
            name='stat',
        ),
        migrations.AddField(
            model_name='plottype',
            name='stat',
            field=models.ManyToManyField(to='data_parser.Stat'),
        ),
        migrations.RemoveField(
            model_name='stat',
            name='depth',
        ),
        migrations.AddField(
            model_name='stat',
            name='depth',
            field=models.ManyToManyField(to='data_parser.Depth'),
        ),
    ]
