# Generated by Django 2.2.7 on 2019-11-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0006_auto_20191128_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='depth',
            new_name='depths',
        ),
    ]
