# Generated by Django 2.2.7 on 2019-11-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0007_auto_20191128_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plottype',
            old_name='stat',
            new_name='stats',
        ),
    ]
