# Generated by Django 2.2.7 on 2019-12-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0008_auto_20191128_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depth',
            name='products',
            field=models.ManyToManyField(related_name='depths', to='data_parser.Product'),
        ),
        migrations.AlterField(
            model_name='plottype',
            name='stats',
            field=models.ManyToManyField(related_name='plot_types', to='data_parser.Stat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datasets',
            field=models.ManyToManyField(related_name='products', to='data_parser.Dataset'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='depths',
            field=models.ManyToManyField(related_name='stats', to='data_parser.Depth'),
        ),
    ]
