# Generated by Django 3.0 on 2019-12-10 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0009_auto_20191202_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=1024)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Area')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Variable')),
            ],
        ),
    ]
