# Generated by Django 3.0 on 2019-12-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0011_auto_20191210_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='product',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
