FROM python:3.7

RUN mkdir /code
COPY . /code
WORKDIR /code

RUN apt-get update -y

RUN apt-get install build-essential -y
RUN apt-get install -y libhdf5-dev libnetcdf-dev netcdf-bin
RUN ln -s /usr/include/hdf5/serial /usr/include/hdf5/include
RUN export HDF5_DIR=/usr/include/hdf5
RUN pip install netCDF4
RUN pip install xarray 

# Build and production mode
RUN apt-get install python3.7-dev -y
RUN apt-get install build-essential -y
RUN apt-get install nginx -y 

# RUN pip install numpy scipy matplotlib ipython jupyter pandas sympy nose

RUN pip install bottleneck 
RUN pip install dask

RUN pip install -r requirements.txt

COPY ./docker/nginx/mysite_nginx.conf /etc/nginx/conf.d/default.conf

CMD ["/bin/bash", "docker/django/launcher.sh"]